(()=>{
const stages=['Novo lead','Em contacto','Proposta enviada','Convertido','Perdido'];
const legacy=s=>s==='Contactado'?'Em contacto':s==='Fechado'?'Convertido':(s||'Novo lead');
const safe=v=>esc(v||'—');
const tel=v=>{let n=String(v||'').replace(/\D/g,'');if(n.startsWith('00'))n=n.slice(2);if(n.length===9)n='351'+n;return n};
let query='',stageFilter='Todos',originFilter='Todas',packFilter='Todos',editing=null;
function age(v){if(!v)return 0;return Math.max(0,Math.floor((Date.now()-new Date(v).getTime())/86400000))}
function ensure(){
 const panel=E('leads'); if(!panel||E('leadTools'))return;
 panel.querySelector('.top').insertAdjacentHTML('afterend',`<div id="leadStats" class="lead-stats"></div><div id="leadTools" class="lead-tools"><input id="leadSearch" placeholder="Pesquisar nome, telemóvel, email ou local"><select id="leadStage"><option>Todos</option>${stages.map(x=>`<option>${x}</option>`).join('')}</select><select id="leadOrigin"><option>Todas</option></select><select id="leadPack"><option>Todos</option></select></div>`);
 E('leadSearch').oninput=e=>{query=e.target.value.toLowerCase();renderL()};
 E('leadStage').onchange=e=>{stageFilter=e.target.value;renderL()};
 E('leadOrigin').onchange=e=>{originFilter=e.target.value;renderL()};
 E('leadPack').onchange=e=>{packFilter=e.target.value;renderL()};
 document.body.insertAdjacentHTML('beforeend',`<div class="modal" id="leadEditModal"><div class="modalbox lead-edit"><div class="top"><h2>Editar lead</h2><button class="btn light" id="closeLeadEdit">Fechar</button></div><div class="form"><label>Nome<input id="elNames"></label><label>Telemóvel<input id="elPhone"></label><label>Email<input id="elEmail" type="email"></label><label>Data do evento<input id="elDate" type="date"></label><label>Local<input id="elVenue"></label><label>Convidados<input id="elGuests" type="number"></label><label>Tipo de evento<input id="elSource"></label><label>Pack<input id="elCampaign"></label><label>Origem<input id="elOrigin"></label><label>Estado<select id="elStatus">${stages.map(x=>`<option>${x}</option>`).join('')}</select></label></div><div class="actions"><button class="btn green" id="elWhatsapp">Contactar pelo WhatsApp</button><button class="btn blue" id="saveLeadEdit">Guardar alterações</button></div></div></div>`);
 E('closeLeadEdit').onclick=()=>E('leadEditModal').classList.remove('on');
 E('saveLeadEdit').onclick=saveEdit; E('elWhatsapp').onclick=()=>contactLead(editing);
 const s=document.createElement('style');s.textContent=`.lead-stats{display:grid;grid-template-columns:repeat(5,1fr);gap:10px;margin:18px 0}.lead-stat{background:#fff;border:1px solid #e5e7eb;border-radius:14px;padding:14px}.lead-stat strong{display:block;font-size:25px;margin-top:4px}.lead-tools{display:grid;grid-template-columns:2fr repeat(3,1fr);gap:9px;margin-bottom:16px}.lead-tools input,.lead-tools select,.lead select{width:100%;padding:10px;border:1px solid #d8dde5;border-radius:9px;background:#fff}.leadgrid{grid-template-columns:repeat(5,minmax(245px,1fr))}.lead{border:1px solid #e7ebf0;box-shadow:0 5px 15px #18202a0a}.lead-head{display:flex;justify-content:space-between;gap:8px}.lead-info{display:grid;gap:5px;margin:10px 0;color:#586477;font-size:13px}.lead-actions{display:grid;gap:7px;margin-top:10px}.lead-actions .btn{width:100%;text-align:center}.lead-alert{background:#fee2e2;color:#a51919;border-radius:99px;padding:4px 7px;font-size:10px;font-weight:800}.lead-edit{width:min(760px,97vw)}@media(max-width:900px){.lead-stats{grid-template-columns:repeat(2,1fr)}.lead-tools{grid-template-columns:1fr 1fr}.leadgrid{grid-template-columns:repeat(5,280px)}}@media(max-width:560px){.lead-stats,.lead-tools{grid-template-columns:1fr}.leadgrid{grid-template-columns:1fr;overflow:visible}.col{min-height:auto}.lead-actions{grid-template-columns:1fr}}`;document.head.appendChild(s);
}
function refreshFilters(){
 const origins=[...new Set(leads.map(x=>x.origin).filter(Boolean))],packs=[...new Set(leads.map(x=>x.campaign).filter(Boolean))];
 if(E('leadOrigin'))E('leadOrigin').innerHTML='<option>Todas</option>'+origins.map(x=>`<option ${x===originFilter?'selected':''}>${safe(x)}</option>`).join('');
 if(E('leadPack'))E('leadPack').innerHTML='<option>Todos</option>'+packs.map(x=>`<option ${x===packFilter?'selected':''}>${safe(x)}</option>`).join('');
}
renderL=function(){
 ensure(); if(!E('leadgrid'))return; refreshFilters();
 E('leadStats').innerHTML=stages.map(s=>`<div class="lead-stat"><small>${s}</small><strong>${leads.filter(x=>legacy(x.status)===s).length}</strong></div>`).join('');
 const filtered=leads.filter(x=>{let st=legacy(x.status),hay=[x.names,x.phone,x.email,x.venue,x.origin,x.campaign,x.source].join(' ').toLowerCase();return(!query||hay.includes(query))&&(stageFilter==='Todos'||st===stageFilter)&&(originFilter==='Todas'||x.origin===originFilter)&&(packFilter==='Todos'||x.campaign===packFilter)});
 E('leadgrid').innerHTML=stages.map(s=>{let list=filtered.filter(x=>legacy(x.status)===s);return`<div class="col"><b>${s} · ${list.length}</b>${list.map(x=>`<div class="lead"><div class="lead-head"><b>${safe(x.names)}</b>${s==='Novo lead'?'<span class="lead-alert">Por contactar</span>':''}</div><div class="lead-info"><span><b>Telemóvel:</b> ${safe(x.phone)}</span><span><b>Email:</b> ${safe(x.email)}</span><span><b>Data:</b> ${safe(x.wedding_date)}</span><span><b>Local:</b> ${safe(x.venue)}</span><span><b>Evento:</b> ${safe(x.source)}</span><span><b>Convidados:</b> ${safe(x.guests)}</span><span><b>Pack:</b> ${safe(x.campaign)}</span><span><b>Origem:</b> ${safe(x.origin)}</span>${s==='Novo lead'?'<span>Recebido há '+age(x.created_at)+' dia(s)</span>':''}</div><select aria-label="Estado do lead" onchange="moveL('${x.id}',this.value)">${stages.map(v=>`<option ${v===s?'selected':''}>${v}</option>`).join('')}</select><div class="lead-actions">${x.phone?`<button class="btn green" onclick="contactLead('${x.id}')">Contactar pelo WhatsApp</button>`:''}<button class="btn light" onclick="editLead('${x.id}')">Editar lead</button>${s==='Convertido'&&x.status!=='Fechado'?`<button class="btn blue" onclick="convertL('${x.id}')">Criar novo serviço</button>`:s==='Convertido'&&x.status==='Fechado'?'<span class="pill good">Serviço criado</span>':''}</div></div>`).join('')||'<p class="muted">Sem leads.</p>'}</div>`}).join('');
};
window.contactLead=id=>{let x=leads.find(v=>v.id===id),p=tel(x?.phone);if(!p)return alert('Este lead não tem telemóvel.');open('https://wa.me/'+p,'_blank')};
window.editLead=id=>{let x=leads.find(v=>v.id===id);if(!x)return;editing=id;[['elNames','names'],['elPhone','phone'],['elEmail','email'],['elDate','wedding_date'],['elVenue','venue'],['elGuests','guests'],['elSource','source'],['elCampaign','campaign'],['elOrigin','origin']].forEach(([a,b])=>E(a).value=x[b]??'');E('elStatus').value=legacy(x.status);E('elWhatsapp').style.display=x.phone?'':'none';E('leadEditModal').classList.add('on')};
async function saveEdit(){if(!editing)return;let p={names:E('elNames').value.trim(),phone:E('elPhone').value.trim()||null,email:E('elEmail').value.trim()||null,wedding_date:E('elDate').value||null,venue:E('elVenue').value.trim()||null,guests:E('elGuests').value?+E('elGuests').value:null,source:E('elSource').value.trim()||null,campaign:E('elCampaign').value.trim()||null,origin:E('elOrigin').value.trim()||null,status:E('elStatus').value,updated_at:new Date().toISOString()};let {error}=await sb.from('leads').update(p).eq('id',editing);if(error)return alert(error.message);E('leadEditModal').classList.remove('on');await loadL()}
window.convertL=async id=>{let x=leads.find(v=>v.id===id);if(!x)return;let conditions=[x.campaign&&('Pack: '+x.campaign),x.source&&('Tipo: '+x.source)].filter(Boolean).join('\n')||null;let {error}=await sb.from('weddings').insert({names:x.names,contact:x.phone||null,email:x.email||null,wedding_date:x.wedding_date||null,venue:x.venue||null,guests:x.guests||null,conditions,origin:x.origin||null,status:'Por preencher',portal_status:'Por preencher',preparation_status:'Por iniciar'});if(error)return alert(error.message);await sb.from('leads').update({status:'Fechado',updated_at:new Date().toISOString()}).eq('id',id);alert('Novo serviço criado na agenda.');await Promise.all([loadW(),loadL()])};
window.moveL=async(id,status)=>{let {error}=await sb.from('leads').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(error)return alert(error.message);await loadL()};
setTimeout(()=>{ensure();renderL()},500);
})();